### ISSUE TITLE
Consider moving Section's methods into a trait

### ISSUE THREAD

**Issue by fitzgen** [luser/rust-test-assembler#3]
Here is what I am imagining:
- Move all of `Section`'s methods to a trait `SectionMethods`
- Make an `impl SectionMethods for Section { ... }`

This will make it nicer to mixin new methods into `Section`, similar to the way @JimBlandy used inheritence and subclassing in the breakpad tests, eg http://searchfox.org/mozilla-central/source/toolkit/crashreporter/google-breakpad/src/common/dwarf/dwarf2reader_cfi_unittest.cc#271

Once this is done, one could add new methods like so:

``` rust
trait CfiMethods: SectionMethods {
    fn cie(self, ...) -> Self {
        // Default trait method implementation here
    }

    fn fde(self, ...) -> Self {
        // Default trait method implementation here
    }

    // Etc...
}

// Nothing else needed because we have defaults for the trait methods
impl CfiMethods for Section {}
```
- The default trait method implementations can use the `SectionMethods` methods
- Returning `Self` allows returning the actual concrete "subclass" type, rather than the "base" type so it allows chaining even with "subclasses" (which is an annoyance that @JimBlandy had with breakpad + subclassing)
- Would it be better to define a `CfiSection` and `impl SectionMethods` and `impl CfiMethods` for `CfiSection`? Wouldn't that provide better namespacing? No, we only get trait methods if they are being `use Trait`ed, so if you don't want them, then don't `use Trait` in that module. Also, what I proposed here allows reuse of the original `SectionMethods` implementation instead of requiring all new types to also implement that trait.

**Comment by luser** [comment]
So here are all the `Section` subclasses I could find in the Breakpad source:
https://chromium.googlesource.com/breakpad/breakpad/+/master/src/common/mac/macho_reader_unittest.cc#501
https://chromium.googlesource.com/breakpad/breakpad/+/master/src/processor/synth_minidump.h
https://chromium.googlesource.com/breakpad/breakpad/+/master/src/common/linux/synth_elf.h
https://chromium.googlesource.com/breakpad/breakpad/+/master/src/common/dwarf/dwarf2reader_test_common.h

One thing that I think won't work with your proposal is that many of these subclasses have their own internal state. Additionally, it seems like we'd actually lose some type safety vs. the C++ version, since many of the subclasses have methods for appending other Section subclasses with special handling (like the stuff in synth_minidump.h).

**Comment by fitzgen** [comment]
Yes, it doesn't assume any extra state, just a collection of helper methods to make writing certain forms easier.

I'm not sure how to handle those things...

**Comment by fitzgen** [comment]
I mean, if everything is a trait, one could always re-implement those traits for their own types, but that is the kind of boilerplate I was hoping to avoid...

**Comment by luser** [comment]
We discussed on IRC maybe adding something so you could do

``` rust
struct MySection {
  section: Section,
}

impl_section_for!(MySection, section);
```

...but I realize that given the existing `Section` API which takes ownership of `self` in all the methods and returns ownership is not really conducive to doing this.

**Comment by luser** [comment]
So it struck me that the C++ examples there have two distinct use cases, they're just conflated by the inheritance. Some of those are "we want new convenience methods on `Section`" and some of those are "we want to encapsulate a `Section` as a new type and late be appended to another `Section`." I think we can support both of those cases without significant changes.

First of all, I realized I had not implemented `Section::Append(const Section&)` from the C++ version, so I implemented `Section::append_section`: https://github.com/luser/rust-test-assembler/commit/2d9cfdd178a770bdd08cb3d98bb0150a729ff2b4 . It takes an `Into<Section>`, so you should be able to write things in the latter class simply by encapsulating a `Section` and then implementing `From<T>` for your type, like:

``` rust
struct MyThing { section: Section }

impl From<MyThing> for Section {
  fn from(t: MyThing) -> Section {
    let MyThing { section, .. } = t;
    section
  }
}

fn do_something() {
  let mut s = Section::new();
  let t = MyThing::new();
  // do something with t
  s = s.append_section(t);
  // do something with s
}
```

It might be a pain to use a `Section` as a member because of the ownership, but if `MyThing` is going to implement its API methods the same way to allow chaining it might not be too bad, something like:

``` rust
impl MyThing {
  fn do_a_thing(self, x: u32) -> MyThing {
    let MyThing { mut section, .. } = self;
    section = section.L32(x);
    MyThing { section: section }
  }
}
```

For the other case (just adding utility methods to `Section`, like in your initial comment), I think that's already handled very nicely by traits. I wrote a test just to prove to myself that it would work well: https://github.com/luser/rust-test-assembler/commit/ed7acbf58a0d3385f5a82bb986b1293163b751b1

Does that all sound reasonable to you? I suppose we'll have to try implementing some real-world uses of these to find out if the API is suitable.

**Comment by luser** [comment]
I started a port of SynthMinidump on my flights to and from Portland, and it seems to be pretty workable with the current API: https://github.com/luser/rust-minidump/blob/master/src/synth_minidump.rs

Given that the "additional helper methods" use case is handled well by traits, and that the "encapsulate Section" use case seems to be workable, I'm going to claim that we don't need to significantly change the API right now.

**Comment by jimblandy** [comment]
This conversation brought up a bunch of angles that hadn't occurred to me, but I still think extension traits aren't quite the right thing. If I wanted to write tests for, say, a TrueType parser, I could certainly write an extension trait that adds methods for building various kinds of TrueType tables and so on to a `Section`. But then those methods would be callable on any `Section` at all, even those representing other sorts of files. I'd like to have types `TrueTypeFile`, `TrueTypeCollectionFile`, and so on, each of which only lets me append things that belong in it.

Would it work to have the dumb `D32`-like methods in a trait, with a default impl for types that implement `AsMut<Section>`? Or perhaps a custom `AsSection` trait, to make the opt-in explicit? Would that run afoul of trait coherence rules?
