### ISSUE TITLE
The Section::start() label is unconstrained

### ISSUE THREAD

**Issue by fitzgen** [luser/rust-test-assembler#4]
It seems to me that this label should always be constant and pointing to the start of the section. Things get a bit trickier when concatenating multiple sections. Perhaps it should be set once `section.get_contents()` is called?

I end up hacking around it by calling `section.start().set_const(0)` right before I get the section contents, but it really feels to me like I shouldn't have to. In this example, I have two labels that are relative to the start of the section (via `mark()`) and they end up without a concrete location unless I explicitly set the start to 0. https://github.com/gimli-rs/gimli/pull/88/commits/0575b2df403161d4b1fba18f83957b1cf92fe349#diff-40fe1838d9c931774e10ee89393a864eR1193

Similar, but slightly smaller example: https://github.com/gimli-rs/gimli/pull/88/commits/ae5a8893fff40d7aa4f3f32e545455f090b8aa3a#diff-40fe1838d9c931774e10ee89393a864eR1280

**Comment by luser** [comment]
I copied this behavior exactly from @JimBlandy's C++ implementation:
https://chromium.googlesource.com/breakpad/breakpad/+/master/src/common/test_assembler.h#264

I understand the reasoning there--the start of a `Section` is intentionally left vague. However, I think having it default to zero seems sensible, so that you can add a `Label` and mark it without having to explicitly set the start. If you want to override the value you should still be able to call `set_const`, like my stackwalker unit tests do to use it as a memory address:
https://github.com/luser/rust-minidump/blob/62fcc3c108cf4f77c7d111426c23959877f637ee/src/stackwalker/x86_unittest.rs#L76

**Comment by jimblandy** [comment]
The reason for that behavior was that I had some cases where I knew the address at which I wanted a byte in the middle of the section to land, and wanted it to compute the start address for me. (I was laying out memory images of stack frames, and I wanted the second or third frame down to be at a particular address.)

If you have two labels both pointing into the same section, you can subtract them. Or, if you know the address at which you want a section to start, you can just set the start label to the value. So why is it helpful for it to have a default?

It just seems like a default makes things less flexible. You can always set the start address when you know it; but there are things you can't do if every section always has a start value.

**Comment by luser** [comment]
If we added a method to `Section` to set the start value that allowed chaining, would that make it easy enough to use that this wouldn't be an issue? If you could do:

``` rust
let s = Section::new()
  .set_start_const(0)
  .D8(...)
  ...
```

 What do you think about that?

**Comment by fitzgen** [comment]
That would work for me.

**Comment by jimblandy** [comment]
> What do you think about that?

I like it!
